-- local cmp = require("cmp")
-- local luasnip = require("luasnip")
--
-- luasnip.config.setup({})
--
-- cmp.setup({
-- 	snippet = {
-- 		expand = function(args)
-- 			luasnip.lsp_expand(args.body)
-- 		end,
-- 	},
-- 	completion = { completeopt = "menu,menuone,noinsert" },
-- 	mapping = cmp.mapping.preset.insert({
-- 		["<C-n>"] = cmp.mapping.select_next_item(),
-- 		["<C-p>"] = cmp.mapping.select_prev_item(),
-- 		["<C-b>"] = cmp.mapping.confirm({ select = true }),
-- 		-- Scroll the documentation window [b]ack / [f]orward
-- 		["<C-s>"] = cmp.mapping.scroll_docs(-4),
-- 		["<C-f>"] = cmp.mapping.scroll_docs(4),
-- 		["<C-Space>"] = cmp.mapping.complete({}),
-- 	}),
-- 	sources = {
-- 		{
-- 			name = "lazydev",
-- 			group_index = 0,
-- 		},
-- 		{ name = "nvim_lsp" },
-- 		{ name = "luasnip" },
-- 		{ name = "path" },
-- 		{ name = "cmp_r" },
-- 		{ name = "vimtex" },
-- 		{ name = "latex_symbols" },
-- 	},
-- })
