require("telescope").load_extension("harpoon")
local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>a", mark.add_file)
vim.keymap.set("n", "<C-e>", ":Telescope harpoon marks<CR>")

vim.keymap.set("n", "w1", function()
	ui.nav_file(1)
end)
vim.keymap.set("n", "w2", function()
	ui.nav_file(2)
end)
vim.keymap.set("n", "w3", function()
	ui.nav_file(3)
end)
vim.keymap.set("n", "w4", function()
	ui.nav_file(4)
end)
